/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.tealium.appcelerator.android;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import com.tealium.library.Key;
import com.tealium.library.Tealium;

@Kroll.module(name = "TealiumAndroid", id = "com.tealium.appcelerator.android")
public class TealiumAndroidModule extends KrollModule {

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TealiumAndroidModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Tealium.initialize(Tealium.Config.create(app, "tealiummobile", "demo",
				"dev").setLibraryLogLevel(Tealium.LogLevel.VERBOSE));
	}

	// Methods
	@Kroll.method
	public void trackView(String viewName, KrollDict data) {
		if (data == null) {
			data = new KrollDict(1);
		}
		data.put(Key.SCREEN_TITLE, viewName);
		Tealium.track(null, data, Tealium.VIEW);
	}

	// Methods
	@Kroll.method
	public void trackEvent(String eventName, KrollDict data) {
		if (data == null) {
			data = new KrollDict(1);
		}
		data.put(Key.LINK_ID, eventName);
		Tealium.track(null, data, Tealium.EVENT);
	}
}
